--createby Bouchaudon Corentin

Insert into Client values (1,'Lenormand','Brian','Link91','kikou91','brian.lenormand@u-psud.fr');
Insert into Client values (2,'Pechdimaldjian','Mathilde','Totoro','123456789','mathilde.pechdimaldjian@u-psud.fr');
Insert into Client values (3,'Bouchaudon','Corentin','Kevindu93','djudjull','corentin.bouchaudon@u-psud.fr');

insert into CategorieClient values (1,'inscrit');
insert into CategorieClient values (2,'premium');
insert into CategorieClient values (3,'administrateur');

insert into CompoClient values (1,1);
insert into CompoClient values (2,2);
insert into CompoClient values (3,3);


insert into CategorieVideo values( 1,'Film');
insert into CategorieVideo values( 2,'Serie');
insert into CategorieVideo values( 3,'Documentaire');


insert into Video values (1,'Star Wars La Menace Fantome','',1,'Avant de devenir un célèbre chevalier Jedi, et bien avant de se révéler l âme la plus noire de la galaxie, Anakin Skywalker est un jeune esclave sur la planète Tatooine. La Force est déjà puissante en lui et il est un remarquable pilote de Podracer. Le maître Jedi Qui-Gon Jinn le découvre et entrevoit alors son immense potentiel.Pendant ce temps, l armée de droïdes de l insatiable Fédération du Commerce a envahi Naboo, une planète pacifique, dans le cadre d n plan secret des Sith visant à accroître leur pouvoir. Pour défendre la reine de Naboo, Amidala, les chevaliers Jedi vont devoir affronter le redoutable Seigneur Sith, Dark Maul.',666,100, 3.99,5.99);
insert into Video values (2,'Star Wars La Guerre des Clones','',2,'Depuis le blocus de la planète Naboo par la Fédération du commerce, la République, gouvernée par le Chancelier Palpatine, connaît une véritable crise. Un groupe de dissidents, mené par le sombre Jedi comte Dooku, manifeste son mécontentement envers le fonctionnement du régime. Le Sénat et la population intergalactique se montrent pour leur part inquiets face à l émergence d une telle menace.Certains sénateurs demandent à ce que la République soit dotée d une solide armée pour empêcher que la situation ne se détériore davantage. Parallèlement, Padmé Amidala, devenue sénatrice, est menacée par les séparatistes et échappe de justesse à un attentat. Le Padawan Anakin Skywalker est chargé de sa protection. Son maître, Obi-Wan Kenobi, part enquêter sur cette tentative de meurtre et découvre la constitution d une mystérieuse armée de clones... ',2,100, 5.99,3.99);
insert into Video values (3,'Star Wars La Revanche Sith','',3,'La Guerre des Clones fait rage. Une franche hostilité oppose désormais le Chancelier Palpatine au Conseil Jedi. Anakin Skywalker, jeune Chevalier Jedi pris entre deux feux, hésite sur la conduite à tenir. Séduit par la promesse d un pouvoir sans précédent, tenté par le côté obscur de la Force, il prête allégeance au maléfique Darth Sidious et devient Dark Vador.Les Seigneurs Sith s unissent alors pour préparer leur revanche, qui commence par l extermination des Jedi. Seuls rescapés du massacre, Yoda et Obi Wan se lancent à la poursuite des Sith. La traque se conclut par un spectaculaire combat au sabre entre Anakin et Obi Wan, qui décidera du sort de la galaxie.',123,100, 3.99,5.99);
insert into Video values (4,'Star Wars La guerre des etoiles','',4,'Il y a bien longtemps, dans une galaxie très lointaine... La guerre civile fait rage entre l Empire galactique et l Alliance rebelle. Capturée par les troupes de choc de l Empereur menées par le sombre et impitoyable Dark Vador, la princesse Leia Organa dissimule les plans de l Etoile Noire, une station spatiale invulnérable, à son droïde R2-D2 avec pour mission de les remettre au Jedi Obi-Wan Kenobi. Accompagné de son fidèle compagnon, le droïde de protocole C-3PO, R2-D2 s échoue sur la planète Tatooine et termine sa quête chez le jeune Luke Skywalker. Rêvant de devenir pilote mais confiné aux travaux de la ferme, ce dernier se lance à la recherche de ce mystérieux Obi-Wan Kenobi, devenu ermite au coeur des montagnes désertiques de Tatooine... ',15000,100, 2.99,4.99);
insert into Video values (5,'Star Wars L empire contre attaque','',5,' Malgré la destruction de l Etoile Noire, l Empire maintient son emprise sur la galaxie, et poursuit sans relâche sa lutte contre l Alliance rebelle. Basés sur la planète glacée de Hoth, les rebelles essuient un assaut des troupes impériales. Parvenus à s échapper, la princesse Leia, Han Solo, Chewbacca et C-3P0 se dirigent vers Bespin, la cité des nuages gouvernée par Lando Calrissian, ancien compagnon de Han. Suivant les instructions d Obi-Wan Kenobi, Luke Skywalker se rend quant à lui vers le système de Dagobah, planète marécageuse où il doit recevoir l enseignement du dernier maître Jedi, Yoda. Apprenant l arrestation de ses compagnons par les stormtroopers de Dark Vador après la trahison de Lando, Luke décide d interrompre son entraînement pour porter secours à ses amis et affronter le sombre seigneur Sith... ',18000,100, 2.99,4.99);
insert into Video values (6,'Star Wars Le retour du Jedi','',6,' L Empire galactique est plus puissant que jamais : la construction de la nouvelle arme, l Etoile de la Mort, menace l univers tout entier... Arrêté après la trahison de Lando Calrissian, Han Solo est remis à l ignoble contrebandier Jabba Le Hutt par le chasseur de primes Boba Fett. Après l échec d une première tentative d évasion menée par la princesse Leia, également arrêtée par Jabba, Luke Skywalker et Lando parviennent à libérer leurs amis.Han, Leia, Chewbacca, C-3PO et Luke, devenu un Jedi, s envolent dès lors pour une mission d extrême importance sur la lune forestière d Endor, afin de détruire le générateur du bouclier de l Etoile de la Mort et permettre une attaque des pilotes de l Alliance rebelle. Conscient d être un danger pour ses compagnons, Luke préfère se rendre aux mains de Dark Vador, son père et ancien Jedi passé du côté obscur de la Force. ',18000,100, 2.99,4.99);
insert into Video values (7,'Star Wars Le reveil de la Force','',7,'Dans une galaxie lointaine, très lointaine, un nouvel épisode de la saga "Star Wars", 30 ans après les événements du "Retour du Jedi"',15000,100, 9.99,12.99);
insert into Video values (8,'Star Wars Les derniers jedi','',8,' Les héros du Réveil de la force rejoignent les figures légendaires de la galaxie dans une aventure épique qui révèle des secrets ancestraux sur la Force et entraîne de surprenantes révélations sur le passé… ',8000,100, 9.99,20.99);
insert into Video values (9,'Interstellar','',0,'Le film raconte les aventures d un groupe d’explorateurs qui utilisent une faille récemment découverte dans l espace-temps afin de repousser les limites humaines et partir à la conquête des distances astronomiques dans un voyage interstellaire.  ',20000,100, 5.99,9.99);
insert into Video values (10,'My Little Pony: Le film','',0,'Quand le menaçant Storm King envahit Canterlot avec le plan de voler la magie aux poneys, le futur même d Equestria est en danger. Cette aventure inédite embarque les poneys à chercher du secours dans un voyage héroïque et plein d actions, au-delà des frontières de leurs foyers, à travers les montagnes magiques, les mondes sous-marins, et même dans un flamboyant bateau pirate volant. ',2,100, 0.99,2.99);
insert into Video values (11,'Mon Voisin Totoro','',0,'Deux petites filles viennent s installer avec leur père dans une grande maison à la campagne afin de se rapprocher de l hôpital ou séjourne leur mère. Elles vont découvrir l existence de créatures merveilleuses, mais très discrètes, les totoros. Le totoro est une créature rare et fascinante, un esprit de la forêt. Il se nourrit de glands et de noix. Il dort le jour, mais les nuits de pleine lune, il aime jouer avec des ocarinas magiques. Il peut voler et est invisible aux yeux des humains. ',5000,100, 3.99,6.99);
insert into Video values (12,'Le Voyage de Chihiro','',0,'Chihiro, dix ans, a tout d une petite fille capricieuse. Elle s apprête à emménager avec ses parents dans une nouvelle demeure.Sur la route, la petite famille se retrouve face à un immense bâtiment rouge au centre duquel s ouvre un long tunnel. De l autre côté du passage se dresse une ville fantôme. Les parents découvrent dans un restaurant désert de nombreux mets succulents et ne tardent pas à se jeter dessus. Ils se retrouvent alors transformés en cochons.Prise de panique, Chihiro s enfuit et se dématérialise progressivement. L énigmatique Haku se charge de lui expliquer le fonctionnement de l univers dans lequel elle vient de pénétrer. Pour sauver ses parents, la fillette va devoir faire face à la terrible sorcière Yubaba, qui arbore les traits dune harpie méphistophélique.',15000,100, 3.99,6.99);
insert into Video values (13,'Baby Driver','',0,'Chauffeur pour des braqueurs de banque, Baby a un truc pour être le meilleur dans sa partie : il roule au rythme de sa propre playlist. Lorsqu’il rencontre la fille de ses rêves, Baby cherche à mettre fin à ses activités criminelles pour revenir dans le droit chemin. Mais il est forcé de travailler pour un grand patron du crime et le braquage tourne mal… Désormais, sa liberté, son avenir avec la fille qu’il aime et sa vie sont en jeu.',11000,100, 8.99,12.99);
insert into Video values (14,'Bienvenue chez les Chtis','',0,'Philippe Abrams est directeur de la poste de Salon-de-Provence. Il est marié à Julie, dont le caractère dépressif lui rend la vie impossible. Pour lui faire plaisir, Philippe fraude afin d obtenir une mutation sur la Côte d Azur. Mais il est démasqué: il sera muté à Bergues, petite ville du Nord.Pour les Abrams, sudistes pleins de préjugés, le Nord c est l horreur, une région glacée, peuplée d êtres rustres, éructant un langage incompréhensible, le "cheutimi". ',2000,100, 3.99,5.99);
insert into Video values (15,'Les 11 Commandements','',0,'Le monde va mal, les humains ne rigolent plus, la situation est grave. Le Dieu de la blague n a plus qu une solution : Michaël Youn et sa bande.Leur mission : accomplir " Les 11 commandements " de la blague pour remettre les peuples sur le droit chemin de la rigolade en repoussant les limites de la connerie. Danser la valse en apesanteur à 15 000 mètres d altitude, inonder une maison pour la transformer en piscine, jouer au beach volley avec une érection contrôlée, faire du roller sous somnifères... Rien n arrête Michaël Youn et sa bande, et en plus, ils le font pour de vrai ! ',500,100, 1.99,3.99);
insert into Video values (16,'Star Trek Discovery','1',1,'Après un siècle de silence, les klingons refont surface. Déterminés à réunifier leur empire, ils déclarent la guerre à la Fédération des planètes unies. Officier en disgrâce de la Starfleet, Michael Burnham se retrouve au centre du conflit.',200,100, 1.99,3.99);
insert into Video values (17,'Star Trek Discovery','1',2,'Après un siècle de silence, les klingons refont surface. Déterminés à réunifier leur empire, ils déclarent la guerre à la Fédération des planètes unies. Officier en disgrâce de la Starfleet, Michael Burnham se retrouve au centre du conflit.',200,100, 1.99,3.99);
insert into Video values (18,'Star Trek Discovery','1',3,'Après un siècle de silence, les klingons refont surface. Déterminés à réunifier leur empire, ils déclarent la guerre à la Fédération des planètes unies. Officier en disgrâce de la Starfleet, Michael Burnham se retrouve au centre du conflit.',200,100, 1.99,3.99);
insert into Video values (19,'Star Trek Discovery','1',4,'Après un siècle de silence, les klingons refont surface. Déterminés à réunifier leur empire, ils déclarent la guerre à la Fédération des planètes unies. Officier en disgrâce de la Starfleet, Michael Burnham se retrouve au centre du conflit.',200,100, 1.99,3.99);
insert into Video values (20,'Star Trek Discovery','1',5,'Après un siècle de silence, les klingons refont surface. Déterminés à réunifier leur empire, ils déclarent la guerre à la Fédération des planètes unies. Officier en disgrâce de la Starfleet, Michael Burnham se retrouve au centre du conflit.',200,100, 1.99,3.99);
insert into Video values (21,'Star Trek Discovery','1',6,'Après un siècle de silence, les klingons refont surface. Déterminés à réunifier leur empire, ils déclarent la guerre à la Fédération des planètes unies. Officier en disgrâce de la Starfleet, Michael Burnham se retrouve au centre du conflit.',200,100, 1.99,3.99);
insert into Video values (22,'Star Trek Discovery','1',7,'Après un siècle de silence, les klingons refont surface. Déterminés à réunifier leur empire, ils déclarent la guerre à la Fédération des planètes unies. Officier en disgrâce de la Starfleet, Michael Burnham se retrouve au centre du conflit.',200,100, 1.99,3.99);
insert into Video values (23,'Star Trek Discovery','1',8,'Après un siècle de silence, les klingons refont surface. Déterminés à réunifier leur empire, ils déclarent la guerre à la Fédération des planètes unies. Officier en disgrâce de la Starfleet, Michael Burnham se retrouve au centre du conflit.',200,100, 1.99,3.99);
insert into Video values (24,'Star Trek Discovery','1',9,'Après un siècle de silence, les klingons refont surface. Déterminés à réunifier leur empire, ils déclarent la guerre à la Fédération des planètes unies. Officier en disgrâce de la Starfleet, Michael Burnham se retrouve au centre du conflit.',200,100, 1.99,3.99);
insert into Video values (25,'Star Trek Discovery','1',10,'Après un siècle de silence, les klingons refont surface. Déterminés à réunifier leur empire, ils déclarent la guerre à la Fédération des planètes unies. Officier en disgrâce de la Starfleet, Michael Burnham se retrouve au centre du conflit.',200,100, 1.99,3.99);
insert into Video values (26,'Star Trek Discovery','1',11,'Après un siècle de silence, les klingons refont surface. Déterminés à réunifier leur empire, ils déclarent la guerre à la Fédération des planètes unies. Officier en disgrâce de la Starfleet, Michael Burnham se retrouve au centre du conflit.',200,100, 1.99,3.99);
insert into Video values (27,'Star Trek Discovery','1',12,'Après un siècle de silence, les klingons refont surface. Déterminés à réunifier leur empire, ils déclarent la guerre à la Fédération des planètes unies. Officier en disgrâce de la Starfleet, Michael Burnham se retrouve au centre du conflit.',200,100, 1.99,3.99);
insert into Video values (28,'Star Trek Discovery','1',13,'Après un siècle de silence, les klingons refont surface. Déterminés à réunifier leur empire, ils déclarent la guerre à la Fédération des planètes unies. Officier en disgrâce de la Starfleet, Michael Burnham se retrouve au centre du conflit.',200,100, 1.99,3.99);
insert into Video values (29,'Star Trek Discovery','1',14,'Après un siècle de silence, les klingons refont surface. Déterminés à réunifier leur empire, ils déclarent la guerre à la Fédération des planètes unies. Officier en disgrâce de la Starfleet, Michael Burnham se retrouve au centre du conflit.',200,100, 1.99,3.99);
insert into Video values (30,'Star Trek Discovery','1',15,'Après un siècle de silence, les klingons refont surface. Déterminés à réunifier leur empire, ils déclarent la guerre à la Fédération des planètes unies. Officier en disgrâce de la Starfleet, Michael Burnham se retrouve au centre du conflit.',200,100, 1.99,3.99);
insert into Video values (31,'Troy: Fall of a City ','1',1,'Dans l Antiquité, l histoire du siège de la ville de Troie, qui dura dix ans, et l histoire d amour entre Hélène et Pâris.',50,100, 2.99,3.99);
insert into Video values (32,'Troy: Fall of a City ','1',2,'Dans l Antiquité, l histoire du siège de la ville de Troie, qui dura dix ans, et l histoire d amour entre Hélène et Pâris.',50,100, 2.99,3.99);
insert into Video values (33,'Troy: Fall of a City ','1',3,'Dans l Antiquité, l histoire du siège de la ville de Troie, qui dura dix ans, et l histoire d amour entre Hélène et Pâris.',50,100, 2.99,3.99);
insert into Video values (34,'Troy: Fall of a City ','1',4,'Dans l Antiquité, l histoire du siège de la ville de Troie, qui dura dix ans, et l histoire d amour entre Hélène et Pâris.',50,100, 2.99,3.99);
insert into Video values (35,'Troy: Fall of a City ','1',5,'Dans l Antiquité, l histoire du siège de la ville de Troie, qui dura dix ans, et l histoire d amour entre Hélène et Pâris.',50,100, 2.99,3.99);
insert into Video values (36,'Troy: Fall of a City ','1',6,'Dans l Antiquité, l histoire du siège de la ville de Troie, qui dura dix ans, et l histoire d amour entre Hélène et Pâris.',50,100, 2.99,3.99);
insert into Video values (37,'Troy: Fall of a City ','1',7,'Dans l Antiquité, l histoire du siège de la ville de Troie, qui dura dix ans, et l histoire d amour entre Hélène et Pâris.',50,100, 2.99,3.99);
insert into Video values (38,'Troy: Fall of a City ','1',8,'Dans l Antiquité, l histoire du siège de la ville de Troie, qui dura dix ans, et l histoire d amour entre Hélène et Pâris.',50,100, 2.99,3.99);
insert into Video values (39,'Altered Carbon','1',1,'Takeshi Kovacs est un ancien soldat et seul survivant d’un groupe de guerriers d élite vaincus lors d’un soulèvement contre le nouvel ordre mondial. Son esprit est emprisonné dans la glace pendant des siècles, jusqu’à ce que Laurens Bancroft, un homme extrêmement riche et vivant depuis plusieurs siècles lui offre la chance de vivre à nouveau. En échange, Kovacs doit résoudre un meurtre ... celui de Bancroft lui-même.',50,100, 2.99,3.99);
insert into Video values (40,'Altered Carbon','1',2,'Takeshi Kovacs est un ancien soldat et seul survivant d’un groupe de guerriers d élite vaincus lors d’un soulèvement contre le nouvel ordre mondial. Son esprit est emprisonné dans la glace pendant des siècles, jusqu’à ce que Laurens Bancroft, un homme extrêmement riche et vivant depuis plusieurs siècles lui offre la chance de vivre à nouveau. En échange, Kovacs doit résoudre un meurtre ... celui de Bancroft lui-même.',50,100, 2.99,3.99);
insert into Video values (41,'Altered Carbon','1',3,'Takeshi Kovacs est un ancien soldat et seul survivant d’un groupe de guerriers d élite vaincus lors d’un soulèvement contre le nouvel ordre mondial. Son esprit est emprisonné dans la glace pendant des siècles, jusqu’à ce que Laurens Bancroft, un homme extrêmement riche et vivant depuis plusieurs siècles lui offre la chance de vivre à nouveau. En échange, Kovacs doit résoudre un meurtre ... celui de Bancroft lui-même.',50,100, 2.99,3.99);
insert into Video values (42,'Altered Carbon','1',4,'Takeshi Kovacs est un ancien soldat et seul survivant d’un groupe de guerriers d élite vaincus lors d’un soulèvement contre le nouvel ordre mondial. Son esprit est emprisonné dans la glace pendant des siècles, jusqu’à ce que Laurens Bancroft, un homme extrêmement riche et vivant depuis plusieurs siècles lui offre la chance de vivre à nouveau. En échange, Kovacs doit résoudre un meurtre ... celui de Bancroft lui-même.',50,100, 2.99,3.99);
insert into Video values (43,'Altered Carbon','1',5,'Takeshi Kovacs est un ancien soldat et seul survivant d’un groupe de guerriers d élite vaincus lors d’un soulèvement contre le nouvel ordre mondial. Son esprit est emprisonné dans la glace pendant des siècles, jusqu’à ce que Laurens Bancroft, un homme extrêmement riche et vivant depuis plusieurs siècles lui offre la chance de vivre à nouveau. En échange, Kovacs doit résoudre un meurtre ... celui de Bancroft lui-même.',50,100, 2.99,3.99);
insert into Video values (44,'Altered Carbon','1',6,'Takeshi Kovacs est un ancien soldat et seul survivant d’un groupe de guerriers d élite vaincus lors d’un soulèvement contre le nouvel ordre mondial. Son esprit est emprisonné dans la glace pendant des siècles, jusqu’à ce que Laurens Bancroft, un homme extrêmement riche et vivant depuis plusieurs siècles lui offre la chance de vivre à nouveau. En échange, Kovacs doit résoudre un meurtre ... celui de Bancroft lui-même.',50,100, 2.99,3.99);
insert into Video values (45,'Altered Carbon','1',7,'Takeshi Kovacs est un ancien soldat et seul survivant d’un groupe de guerriers d élite vaincus lors d’un soulèvement contre le nouvel ordre mondial. Son esprit est emprisonné dans la glace pendant des siècles, jusqu’à ce que Laurens Bancroft, un homme extrêmement riche et vivant depuis plusieurs siècles lui offre la chance de vivre à nouveau. En échange, Kovacs doit résoudre un meurtre ... celui de Bancroft lui-même.',50,100, 2.99,3.99);
insert into Video values (46,'Altered Carbon','1',8,'Takeshi Kovacs est un ancien soldat et seul survivant d’un groupe de guerriers d élite vaincus lors d’un soulèvement contre le nouvel ordre mondial. Son esprit est emprisonné dans la glace pendant des siècles, jusqu’à ce que Laurens Bancroft, un homme extrêmement riche et vivant depuis plusieurs siècles lui offre la chance de vivre à nouveau. En échange, Kovacs doit résoudre un meurtre ... celui de Bancroft lui-même.',50,100, 2.99,3.99);
insert into Video values (47,'Altered Carbon','1',9,'Takeshi Kovacs est un ancien soldat et seul survivant d’un groupe de guerriers d élite vaincus lors d’un soulèvement contre le nouvel ordre mondial. Son esprit est emprisonné dans la glace pendant des siècles, jusqu’à ce que Laurens Bancroft, un homme extrêmement riche et vivant depuis plusieurs siècles lui offre la chance de vivre à nouveau. En échange, Kovacs doit résoudre un meurtre ... celui de Bancroft lui-même.',50,100, 2.99,3.99);
insert into Video values (48,'Altered Carbon','1',10,'Takeshi Kovacs est un ancien soldat et seul survivant d’un groupe de guerriers d élite vaincus lors d’un soulèvement contre le nouvel ordre mondial. Son esprit est emprisonné dans la glace pendant des siècles, jusqu’à ce que Laurens Bancroft, un homme extrêmement riche et vivant depuis plusieurs siècles lui offre la chance de vivre à nouveau. En échange, Kovacs doit résoudre un meurtre ... celui de Bancroft lui-même.',50,100, 2.99,3.99);
insert into Video values (49,'Sherlok','1',1,'Les aventures de Sherlock Holmes et de son acolyte de toujours, le docteur Watson, sont transposées au XXIème siècle...',300,100, 2.99,3.99);
insert into Video values (50,'Sherlok','1',2,'Les aventures de Sherlock Holmes et de son acolyte de toujours, le docteur Watson, sont transposées au XXIème siècle...',300,100, 2.99,3.99);
insert into Video values (51,'Sherlok','1',3,'Les aventures de Sherlock Holmes et de son acolyte de toujours, le docteur Watson, sont transposées au XXIème siècle...',300,100, 2.99,3.99);
insert into Video values (52,'Sherlok','2',1,'Les aventures de Sherlock Holmes et de son acolyte de toujours, le docteur Watson, sont transposées au XXIème siècle...',300,100, 2.99,3.99);
insert into Video values (53,'Sherlok','2',2,'Les aventures de Sherlock Holmes et de son acolyte de toujours, le docteur Watson, sont transposées au XXIème siècle...',300,100, 2.99,3.99);
insert into Video values (54,'Sherlok','2',3,'Les aventures de Sherlock Holmes et de son acolyte de toujours, le docteur Watson, sont transposées au XXIème siècle...',300,100, 2.99,3.99);
insert into Video values (55,'Sherlok','3',1,'Les aventures de Sherlock Holmes et de son acolyte de toujours, le docteur Watson, sont transposées au XXIème siècle...',300,100, 2.99,3.99);
insert into Video values (56,'Sherlok','3',2,'Les aventures de Sherlock Holmes et de son acolyte de toujours, le docteur Watson, sont transposées au XXIème siècle...',300,100, 2.99,3.99);
insert into Video values (57,'Sherlok','3',3,'Les aventures de Sherlock Holmes et de son acolyte de toujours, le docteur Watson, sont transposées au XXIème siècle...',300,100, 2.99,3.99);
insert into Video values (58,'Sherlok','4',1,'Les aventures de Sherlock Holmes et de son acolyte de toujours, le docteur Watson, sont transposées au XXIème siècle...',300,100, 2.99,3.99);
insert into Video values (59,'Sherlok','4',1,'Les aventures de Sherlock Holmes et de son acolyte de toujours, le docteur Watson, sont transposées au XXIème siècle...',300,100, 2.99,3.99);
insert into Video values (60,'Sherlok','4',1,'Les aventures de Sherlock Holmes et de son acolyte de toujours, le docteur Watson, sont transposées au XXIème siècle...',300,100, 2.99,3.99);
insert into Video values (61,'Black Mirror','1',1,'Chaque épisode de cette anthologie montre la dépendance des hommes vis-à-vis de tout ce qui a un écran...',250,100, 2.99,3.99);
insert into Video values (62,'Black Mirror','1',2,'Chaque épisode de cette anthologie montre la dépendance des hommes vis-à-vis de tout ce qui a un écran...',250,100, 2.99,3.99);
insert into Video values (63,'Black Mirror','1',3,'Chaque épisode de cette anthologie montre la dépendance des hommes vis-à-vis de tout ce qui a un écran...',250,100, 2.99,3.99);
insert into Video values (64,'Black Mirror','2',1,'Chaque épisode de cette anthologie montre la dépendance des hommes vis-à-vis de tout ce qui a un écran...',250,100, 2.99,3.99);
insert into Video values (65,'Black Mirror','2',2,'Chaque épisode de cette anthologie montre la dépendance des hommes vis-à-vis de tout ce qui a un écran...',250,100, 2.99,3.99);
insert into Video values (66,'Black Mirror','2',3,'Chaque épisode de cette anthologie montre la dépendance des hommes vis-à-vis de tout ce qui a un écran...',250,100, 2.99,3.99);
insert into Video values (67,'Black Mirror','2',4,'Chaque épisode de cette anthologie montre la dépendance des hommes vis-à-vis de tout ce qui a un écran...',250,100, 2.99,3.99);
insert into Video values (68,'Black Mirror','3',1,'Chaque épisode de cette anthologie montre la dépendance des hommes vis-à-vis de tout ce qui a un écran...',250,100, 2.99,3.99);
insert into Video values (69,'Black Mirror','3',2,'Chaque épisode de cette anthologie montre la dépendance des hommes vis-à-vis de tout ce qui a un écran...',250,100, 2.99,3.99);
insert into Video values (70,'Black Mirror','3',3,'Chaque épisode de cette anthologie montre la dépendance des hommes vis-à-vis de tout ce qui a un écran...',250,100, 2.99,3.99);
insert into Video values (71,'Black Mirror','3',4,'Chaque épisode de cette anthologie montre la dépendance des hommes vis-à-vis de tout ce qui a un écran...',250,100, 2.99,3.99);
insert into Video values (72,'Black Mirror','3',5,'Chaque épisode de cette anthologie montre la dépendance des hommes vis-à-vis de tout ce qui a un écran...',250,100, 2.99,3.99);
insert into Video values (73,'Black Mirror','3',6,'Chaque épisode de cette anthologie montre la dépendance des hommes vis-à-vis de tout ce qui a un écran...',250,100, 2.99,3.99);
insert into Video values (74,'Black Mirror','4',1,'Chaque épisode de cette anthologie montre la dépendance des hommes vis-à-vis de tout ce qui a un écran...',250,100, 2.99,3.99);
insert into Video values (75,'Black Mirror','4',2,'Chaque épisode de cette anthologie montre la dépendance des hommes vis-à-vis de tout ce qui a un écran...',250,100, 2.99,3.99);
insert into Video values (76,'Black Mirror','4',3,'Chaque épisode de cette anthologie montre la dépendance des hommes vis-à-vis de tout ce qui a un écran...',250,100, 2.99,3.99);
insert into Video values (77,'Black Mirror','4',4,'Chaque épisode de cette anthologie montre la dépendance des hommes vis-à-vis de tout ce qui a un écran...',250,100, 2.99,3.99);
insert into Video values (78,'Black Mirror','4',5,'Chaque épisode de cette anthologie montre la dépendance des hommes vis-à-vis de tout ce qui a un écran...',250,100, 2.99,3.99);
insert into Video values (79,'Black Mirror','4',6,'Chaque épisode de cette anthologie montre la dépendance des hommes vis-à-vis de tout ce qui a un écran...',250,100, 2.99,3.99);
insert into Video values (80,'Stranger Things','1',1,'A Hawkins, en 1983 dans l Indiana. Lorsque Will Byers disparaît de son domicile, ses amis se lancent dans une recherche semée d’embûches pour le retrouver. Dans leur quête de réponses, les garçons rencontrent une étrange jeune fille en fuite. Les garçons se lient d amitié avec la demoiselle tatouée du chiffre 11 sur son poignet et au crâne rasé et découvrent petit à petit les détails sur son inquiétante situation. Elle est peut-être la clé de tous les mystères qui se cachent dans cette petite ville en apparence tranquille…',500,100, 2.99,3.99);
insert into Video values (81,'Stranger Things','1',2,'A Hawkins, en 1983 dans l Indiana. Lorsque Will Byers disparaît de son domicile, ses amis se lancent dans une recherche semée d’embûches pour le retrouver. Dans leur quête de réponses, les garçons rencontrent une étrange jeune fille en fuite. Les garçons se lient d amitié avec la demoiselle tatouée du chiffre 11 sur son poignet et au crâne rasé et découvrent petit à petit les détails sur son inquiétante situation. Elle est peut-être la clé de tous les mystères qui se cachent dans cette petite ville en apparence tranquille…',500,100, 2.99,3.99);
insert into Video values (82,'Stranger Things','1',3,'A Hawkins, en 1983 dans l Indiana. Lorsque Will Byers disparaît de son domicile, ses amis se lancent dans une recherche semée d’embûches pour le retrouver. Dans leur quête de réponses, les garçons rencontrent une étrange jeune fille en fuite. Les garçons se lient d amitié avec la demoiselle tatouée du chiffre 11 sur son poignet et au crâne rasé et découvrent petit à petit les détails sur son inquiétante situation. Elle est peut-être la clé de tous les mystères qui se cachent dans cette petite ville en apparence tranquille…',500,100, 2.99,3.99);
insert into Video values (83,'Stranger Things','1',4,'A Hawkins, en 1983 dans l Indiana. Lorsque Will Byers disparaît de son domicile, ses amis se lancent dans une recherche semée d’embûches pour le retrouver. Dans leur quête de réponses, les garçons rencontrent une étrange jeune fille en fuite. Les garçons se lient d amitié avec la demoiselle tatouée du chiffre 11 sur son poignet et au crâne rasé et découvrent petit à petit les détails sur son inquiétante situation. Elle est peut-être la clé de tous les mystères qui se cachent dans cette petite ville en apparence tranquille…',500,100, 2.99,3.99);
insert into Video values (84,'Stranger Things','1',5,'A Hawkins, en 1983 dans l Indiana. Lorsque Will Byers disparaît de son domicile, ses amis se lancent dans une recherche semée d’embûches pour le retrouver. Dans leur quête de réponses, les garçons rencontrent une étrange jeune fille en fuite. Les garçons se lient d amitié avec la demoiselle tatouée du chiffre 11 sur son poignet et au crâne rasé et découvrent petit à petit les détails sur son inquiétante situation. Elle est peut-être la clé de tous les mystères qui se cachent dans cette petite ville en apparence tranquille…',500,100, 2.99,3.99);
insert into Video values (85,'Stranger Things','1',6,'A Hawkins, en 1983 dans l Indiana. Lorsque Will Byers disparaît de son domicile, ses amis se lancent dans une recherche semée d’embûches pour le retrouver. Dans leur quête de réponses, les garçons rencontrent une étrange jeune fille en fuite. Les garçons se lient d amitié avec la demoiselle tatouée du chiffre 11 sur son poignet et au crâne rasé et découvrent petit à petit les détails sur son inquiétante situation. Elle est peut-être la clé de tous les mystères qui se cachent dans cette petite ville en apparence tranquille…',500,100, 2.99,3.99);
insert into Video values (86,'Stranger Things','1',7,'A Hawkins, en 1983 dans l Indiana. Lorsque Will Byers disparaît de son domicile, ses amis se lancent dans une recherche semée d’embûches pour le retrouver. Dans leur quête de réponses, les garçons rencontrent une étrange jeune fille en fuite. Les garçons se lient d amitié avec la demoiselle tatouée du chiffre 11 sur son poignet et au crâne rasé et découvrent petit à petit les détails sur son inquiétante situation. Elle est peut-être la clé de tous les mystères qui se cachent dans cette petite ville en apparence tranquille…',500,100, 2.99,3.99);
insert into Video values (87,'Stranger Things','1',8,'A Hawkins, en 1983 dans l Indiana. Lorsque Will Byers disparaît de son domicile, ses amis se lancent dans une recherche semée d’embûches pour le retrouver. Dans leur quête de réponses, les garçons rencontrent une étrange jeune fille en fuite. Les garçons se lient d amitié avec la demoiselle tatouée du chiffre 11 sur son poignet et au crâne rasé et découvrent petit à petit les détails sur son inquiétante situation. Elle est peut-être la clé de tous les mystères qui se cachent dans cette petite ville en apparence tranquille…',500,100, 2.99,3.99);
insert into Video values (88,'Stranger Things','2',1,'A Hawkins, en 1983 dans l Indiana. Lorsque Will Byers disparaît de son domicile, ses amis se lancent dans une recherche semée d’embûches pour le retrouver. Dans leur quête de réponses, les garçons rencontrent une étrange jeune fille en fuite. Les garçons se lient d amitié avec la demoiselle tatouée du chiffre 11 sur son poignet et au crâne rasé et découvrent petit à petit les détails sur son inquiétante situation. Elle est peut-être la clé de tous les mystères qui se cachent dans cette petite ville en apparence tranquille…',500,100, 2.99,3.99);
insert into Video values (89,'Stranger Things','2',2,'A Hawkins, en 1983 dans l Indiana. Lorsque Will Byers disparaît de son domicile, ses amis se lancent dans une recherche semée d’embûches pour le retrouver. Dans leur quête de réponses, les garçons rencontrent une étrange jeune fille en fuite. Les garçons se lient d amitié avec la demoiselle tatouée du chiffre 11 sur son poignet et au crâne rasé et découvrent petit à petit les détails sur son inquiétante situation. Elle est peut-être la clé de tous les mystères qui se cachent dans cette petite ville en apparence tranquille…',500,100, 2.99,3.99);
insert into Video values (90,'Stranger Things','2',3,'A Hawkins, en 1983 dans l Indiana. Lorsque Will Byers disparaît de son domicile, ses amis se lancent dans une recherche semée d’embûches pour le retrouver. Dans leur quête de réponses, les garçons rencontrent une étrange jeune fille en fuite. Les garçons se lient d amitié avec la demoiselle tatouée du chiffre 11 sur son poignet et au crâne rasé et découvrent petit à petit les détails sur son inquiétante situation. Elle est peut-être la clé de tous les mystères qui se cachent dans cette petite ville en apparence tranquille…',500,100, 2.99,3.99);
insert into Video values (91,'Stranger Things','2',4,'A Hawkins, en 1983 dans l Indiana. Lorsque Will Byers disparaît de son domicile, ses amis se lancent dans une recherche semée d’embûches pour le retrouver. Dans leur quête de réponses, les garçons rencontrent une étrange jeune fille en fuite. Les garçons se lient d amitié avec la demoiselle tatouée du chiffre 11 sur son poignet et au crâne rasé et découvrent petit à petit les détails sur son inquiétante situation. Elle est peut-être la clé de tous les mystères qui se cachent dans cette petite ville en apparence tranquille…',500,100, 2.99,3.99);
insert into Video values (92,'Stranger Things','2',5,'A Hawkins, en 1983 dans l Indiana. Lorsque Will Byers disparaît de son domicile, ses amis se lancent dans une recherche semée d’embûches pour le retrouver. Dans leur quête de réponses, les garçons rencontrent une étrange jeune fille en fuite. Les garçons se lient d amitié avec la demoiselle tatouée du chiffre 11 sur son poignet et au crâne rasé et découvrent petit à petit les détails sur son inquiétante situation. Elle est peut-être la clé de tous les mystères qui se cachent dans cette petite ville en apparence tranquille…',500,100,2.99,3.99);
insert into Video values (93,'Stranger Things','2',6,'A Hawkins, en 1983 dans l Indiana. Lorsque Will Byers disparaît de son domicile, ses amis se lancent dans une recherche semée d’embûches pour le retrouver. Dans leur quête de réponses, les garçons rencontrent une étrange jeune fille en fuite. Les garçons se lient d amitié avec la demoiselle tatouée du chiffre 11 sur son poignet et au crâne rasé et découvrent petit à petit les détails sur son inquiétante situation. Elle est peut-être la clé de tous les mystères qui se cachent dans cette petite ville en apparence tranquille…',500,100, 2.99,3.99);
insert into Video values (94,'Stranger Things','2',7,'A Hawkins, en 1983 dans l Indiana. Lorsque Will Byers disparaît de son domicile, ses amis se lancent dans une recherche semée d’embûches pour le retrouver. Dans leur quête de réponses, les garçons rencontrent une étrange jeune fille en fuite. Les garçons se lient d amitié avec la demoiselle tatouée du chiffre 11 sur son poignet et au crâne rasé et découvrent petit à petit les détails sur son inquiétante situation. Elle est peut-être la clé de tous les mystères qui se cachent dans cette petite ville en apparence tranquille…',500,100, 2.99,3.99);
insert into Video values (95,'Stranger Things','2',8,'A Hawkins, en 1983 dans l Indiana. Lorsque Will Byers disparaît de son domicile, ses amis se lancent dans une recherche semée d’embûches pour le retrouver. Dans leur quête de réponses, les garçons rencontrent une étrange jeune fille en fuite. Les garçons se lient d amitié avec la demoiselle tatouée du chiffre 11 sur son poignet et au crâne rasé et découvrent petit à petit les détails sur son inquiétante situation. Elle est peut-être la clé de tous les mystères qui se cachent dans cette petite ville en apparence tranquille…',500,100, 2.99,3.99);
insert into Video values (96,'Stranger Things','2',9,'A Hawkins, en 1983 dans l Indiana. Lorsque Will Byers disparaît de son domicile, ses amis se lancent dans une recherche semée d’embûches pour le retrouver. Dans leur quête de réponses, les garçons rencontrent une étrange jeune fille en fuite. Les garçons se lient d amitié avec la demoiselle tatouée du chiffre 11 sur son poignet et au crâne rasé et découvrent petit à petit les détails sur son inquiétante situation. Elle est peut-être la clé de tous les mystères qui se cachent dans cette petite ville en apparence tranquille…',500,100, 2.99,3.99);
insert into Video values (97,'Systeme Solaire, Incroyable Histoire','',0,'La nature même de notre Terre est un véritable miracle, et ce qui reste encore l un des plus grands mystères de l astronomie commence, peu à peu, à se dévoiler... C est un fait : grâce à des preuves venues de planètes extérieures à notre système solaire, les astronomes écrivent une nouvelle histoire de notre univers, un véritable conte infernal, rythmé par le chaos et le tumulte... Car le chemin fut long et mouvementé pour que nos planètes se stabilisent à la place qu elles occupent aujourd hui dans l environnement de notre Terre, permettant à la vie d y éclore.',100,100, 3.99,8.99);
insert into Video values (98,'Prise d otages du vol Alger-Paris','',0,'En 1994, la veille de Noël, un Airbus transportant 177 passagers et 15 tonnes de kérosène extrêmement inflammable explose au-dessus de Paris : une pluie de débris incandescents s abat sur la Ville Lumière. Ce scénario catastrophe... ne s est jamais produit, car les quatre terroristes algériens qui ont détourné le vol Air France 8969 n ont heureusement pas pu le mener à son terme.',100,100, 3.99,8.99);
insert into Video values (99,'Horizon Pacifique','',0,'A première vue, Loretta est une femme polynésienne comme beaucoup d autres. Sa maison, les courses au magasin, le jardin, les chiens accaparent une partie de son temps. Mais une toute petite partie seulement, car vous la trouverez plus souvent une gaffe, des hameçons ou un couteau à la main, vêtue d un gros ciré et de bottes en caoutchouc plutôt que d un pareo et d escarpins, pataugeant dans l eau salé, le sang de poissons du large ou la glace pilée. Partons à la rencontre de Loretta, la seule femme polynésienne embarquée sur un palangrier et qui fait mentir la sacro-sainte règle de tout marin pêcheur : «Pas de femme à bord !»',100,100, 3.99,8.99);
insert into Video values (100,'L homme sur Mars','',0,'A première vue, Loretta est une femme polynésienne comme beaucoup d autres. Sa maison, les courses au magasin, le jardin, les chiens accaparent une partie de son temps. Mais une toute petite partie seulement, car vous la trouverez plus souvent une gaffe, des hameçons ou un couteau à la main, vêtue d un gros ciré et de bottes en caoutchouc plutôt que d un pareo et d escarpins, pataugeant dans l eau salé, le sang de poissons du large ou la glace pilée. Partons à la rencontre de Loretta, la seule femme polynésienne embarquée sur un palangrier et qui fait mentir la sacro-sainte règle de tout marin pêcheur : «Pas de femme à bord !»',100,100, 3.99,8.99);

insert into CompoVideo values (1,1);
insert into CompoVideo values (2,1);
insert into CompoVideo values (3,1);
insert into CompoVideo values (4,1);
insert into CompoVideo values (5,1);
insert into CompoVideo values (6,1);
insert into CompoVideo values (7,1);
insert into CompoVideo values (8,1);
insert into CompoVideo values (9,1);
insert into CompoVideo values (10,1);
insert into CompoVideo values (11,1);
insert into CompoVideo values (12,1);
insert into CompoVideo values (13,1);
insert into CompoVideo values (14,1);
insert into CompoVideo values (15,1);
insert into CompoVideo values (16,2);
insert into CompoVideo values (17,2);
insert into CompoVideo values (18,2);
insert into CompoVideo values (19,2);
insert into CompoVideo values (20,2);
insert into CompoVideo values (21,2);
insert into CompoVideo values (22,2);
insert into CompoVideo values (23,2);
insert into CompoVideo values (24,2);
insert into CompoVideo values (25,2);
insert into CompoVideo values (26,2);
insert into CompoVideo values (27,2);
insert into CompoVideo values (28,2);
insert into CompoVideo values (29,2);
insert into CompoVideo values (30,2);
insert into CompoVideo values (31,2);
insert into CompoVideo values (32,2);
insert into CompoVideo values (33,2);
insert into CompoVideo values (34,2);
insert into CompoVideo values (35,2);
insert into CompoVideo values (36,2);
insert into CompoVideo values (37,2);
insert into CompoVideo values (38,2);
insert into CompoVideo values (39,2);
insert into CompoVideo values (40,2);
insert into CompoVideo values (41,2);
insert into CompoVideo values (42,2);
insert into CompoVideo values (43,2);
insert into CompoVideo values (44,2);
insert into CompoVideo values (45,2);
insert into CompoVideo values (46,2);
insert into CompoVideo values (47,2);
insert into CompoVideo values (48,2);
insert into CompoVideo values (49,2);
insert into CompoVideo values (50,2);
insert into CompoVideo values (51,2);
insert into CompoVideo values (52,2);
insert into CompoVideo values (53,2);
insert into CompoVideo values (54,2);
insert into CompoVideo values (55,2);
insert into CompoVideo values (56,2);
insert into CompoVideo values (57,2);
insert into CompoVideo values (58,2);
insert into CompoVideo values (59,2);
insert into CompoVideo values (60,2);
insert into CompoVideo values (61,2);
insert into CompoVideo values (62,2);
insert into CompoVideo values (63,2);
insert into CompoVideo values (64,2);
insert into CompoVideo values (65,2);
insert into CompoVideo values (66,2);
insert into CompoVideo values (67,2);
insert into CompoVideo values (68,2);
insert into CompoVideo values (69,2);
insert into CompoVideo values (70,2);
insert into CompoVideo values (71,2);
insert into CompoVideo values (72,2);
insert into CompoVideo values (73,2);
insert into CompoVideo values (74,2);
insert into CompoVideo values (75,2);
insert into CompoVideo values (76,2);
insert into CompoVideo values (77,2);
insert into CompoVideo values (78,2);
insert into CompoVideo values (79,2);
insert into CompoVideo values (80,2);
insert into CompoVideo values (81,2);
insert into CompoVideo values (82,2);
insert into CompoVideo values (83,2);
insert into CompoVideo values (84,2);
insert into CompoVideo values (85,2);
insert into CompoVideo values (86,2);
insert into CompoVideo values (87,2);
insert into CompoVideo values (88,2);
insert into CompoVideo values (89,2);
insert into CompoVideo values (90,2);
insert into CompoVideo values (91,2);
insert into CompoVideo values (92,2);
insert into CompoVideo values (93,2);
insert into CompoVideo values (94,2);
insert into CompoVideo values (95,2);
insert into CompoVideo values (96,2);
insert into CompoVideo values (97,3);
insert into CompoVideo values (98,3);
insert into CompoVideo values (99,3);
insert into CompoVideo values (100,3);

insert into MotClef values(1,'Aventure');
insert into MotClef values(2,'Action');
insert into MotClef values(3,'Science-Fiction');
insert into MotClef values(4,'Enfant');
insert into MotClef values(5,'Animation');
insert into MotClef values(6,'Fantastique');
insert into MotClef values(7,'Policier');
insert into MotClef values(8,'Comédie');
insert into MotClef values(9,'Drame');
insert into MotClef values(10,'Historique');
insert into MotClef values(11,'Thriller');
insert into MotClef values(12,'Information');

insert into MotClefVideo values (1,1);
insert into MotClefVideo values (1,2);
insert into MotClefVideo values (1,3);
insert into MotClefVideo values (2,1);
insert into MotClefVideo values (2,2);
insert into MotClefVideo values (2,3);
insert into MotClefVideo values (3,1);
insert into MotClefVideo values (3,2);
insert into MotClefVideo values (3,3);
insert into MotClefVideo values (4,1);
insert into MotClefVideo values (4,2);
insert into MotClefVideo values (4,3);
insert into MotClefVideo values (5,1);
insert into MotClefVideo values (5,2);
insert into MotClefVideo values (5,3);
insert into MotClefVideo values (6,1);
insert into MotClefVideo values (6,2);
insert into MotClefVideo values (6,3);
insert into MotClefVideo values (7,1);
insert into MotClefVideo values (7,2);
insert into MotClefVideo values (7,3);
insert into MotClefVideo values (8,1);
insert into MotClefVideo values (8,2);
insert into MotClefVideo values (8,3);
insert into MotClefVideo values (9,3);
insert into MotClefVideo values (9,9);
insert into MotClefVideo values (10,4);
insert into MotClefVideo values (10,5);
insert into MotClefVideo values (10,8);
insert into MotClefVideo values (11,1);
insert into MotClefVideo values (11,5);
insert into MotClefVideo values (12,1);
insert into MotClefVideo values (12,5);
insert into MotClefVideo values (13,2);
insert into MotClefVideo values (13,7);
insert into MotClefVideo values (13,8);
insert into MotClefVideo values (14,8);
insert into MotClefVideo values (15,8);
insert into MotClefVideo values (16,1);
insert into MotClefVideo values (16,2);
insert into MotClefVideo values (16,3);
insert into MotClefVideo values (17,1);
insert into MotClefVideo values (17,2);
insert into MotClefVideo values (17,3);
insert into MotClefVideo values (18,1);
insert into MotClefVideo values (18,2);
insert into MotClefVideo values (18,3);
insert into MotClefVideo values (19,1);
insert into MotClefVideo values (19,2);
insert into MotClefVideo values (19,3);
insert into MotClefVideo values (20,1);
insert into MotClefVideo values (20,2);
insert into MotClefVideo values (20,3);
insert into MotClefVideo values (21,1);
insert into MotClefVideo values (21,2);
insert into MotClefVideo values (21,3);
insert into MotClefVideo values (22,1);
insert into MotClefVideo values (22,2);
insert into MotClefVideo values (22,3);
insert into MotClefVideo values (23,1);
insert into MotClefVideo values (23,2);
insert into MotClefVideo values (23,3);
insert into MotClefVideo values (24,1);
insert into MotClefVideo values (24,2);
insert into MotClefVideo values (24,3);
insert into MotClefVideo values (25,1);
insert into MotClefVideo values (25,2);
insert into MotClefVideo values (25,3);
insert into MotClefVideo values (26,1);
insert into MotClefVideo values (26,2);
insert into MotClefVideo values (26,3);
insert into MotClefVideo values (27,1);
insert into MotClefVideo values (27,2);
insert into MotClefVideo values (27,3);
insert into MotClefVideo values (28,1);
insert into MotClefVideo values (28,2);
insert into MotClefVideo values (28,3);
insert into MotClefVideo values (29,1);
insert into MotClefVideo values (29,2);
insert into MotClefVideo values (29,3);
insert into MotClefVideo values (30,1);
insert into MotClefVideo values (30,2);
insert into MotClefVideo values (30,3);
insert into MotClefVideo values (31,9);
insert into MotClefVideo values (31,10);
insert into MotClefVideo values (32,9);
insert into MotClefVideo values (32,10);
insert into MotClefVideo values (33,9);
insert into MotClefVideo values (33,10);
insert into MotClefVideo values (34,9);
insert into MotClefVideo values (34,10);
insert into MotClefVideo values (35,9);
insert into MotClefVideo values (35,10);
insert into MotClefVideo values (36,9);
insert into MotClefVideo values (36,10);
insert into MotClefVideo values (37,9);
insert into MotClefVideo values (37,10);
insert into MotClefVideo values (38,9);
insert into MotClefVideo values (38,10);
insert into MotClefVideo values (39,3);
insert into MotClefVideo values (39,7);
insert into MotClefVideo values (39,11);
insert into MotClefVideo values (40,3);
insert into MotClefVideo values (40,7);
insert into MotClefVideo values (40,11);
insert into MotClefVideo values (41,3);
insert into MotClefVideo values (41,7);
insert into MotClefVideo values (41,11);
insert into MotClefVideo values (42,3);
insert into MotClefVideo values (42,7);
insert into MotClefVideo values (42,11);
insert into MotClefVideo values (43,3);
insert into MotClefVideo values (43,7);
insert into MotClefVideo values (43,11);
insert into MotClefVideo values (44,3);
insert into MotClefVideo values (44,7);
insert into MotClefVideo values (44,11);
insert into MotClefVideo values (45,3);
insert into MotClefVideo values (45,7);
insert into MotClefVideo values (45,11);
insert into MotClefVideo values (46,3);
insert into MotClefVideo values (46,7);
insert into MotClefVideo values (46,11);
insert into MotClefVideo values (47,3);
insert into MotClefVideo values (47,7);
insert into MotClefVideo values (47,11);
insert into MotClefVideo values (48,3);
insert into MotClefVideo values (48,7);
insert into MotClefVideo values (48,11);
insert into MotClefVideo values (49,1);
insert into MotClefVideo values (49,7);
insert into MotClefVideo values (49,9);
insert into MotClefVideo values (50,1);
insert into MotClefVideo values (50,7);
insert into MotClefVideo values (50,9);
insert into MotClefVideo values (51,1);
insert into MotClefVideo values (51,7);
insert into MotClefVideo values (51,9);
insert into MotClefVideo values (52,1);
insert into MotClefVideo values (52,7);
insert into MotClefVideo values (52,9);
insert into MotClefVideo values (53,1);
insert into MotClefVideo values (53,7);
insert into MotClefVideo values (53,9);
insert into MotClefVideo values (54,1);
insert into MotClefVideo values (54,7);
insert into MotClefVideo values (54,9);
insert into MotClefVideo values (55,1);
insert into MotClefVideo values (55,7);
insert into MotClefVideo values (55,9);
insert into MotClefVideo values (56,1);
insert into MotClefVideo values (56,7);
insert into MotClefVideo values (56,9);
insert into MotClefVideo values (57,1);
insert into MotClefVideo values (57,7);
insert into MotClefVideo values (57,9);
insert into MotClefVideo values (58,1);
insert into MotClefVideo values (58,7);
insert into MotClefVideo values (58,9);
insert into MotClefVideo values (59,1);
insert into MotClefVideo values (59,7);
insert into MotClefVideo values (59,9);
insert into MotClefVideo values (60,1);
insert into MotClefVideo values (60,7);
insert into MotClefVideo values (60,9);
insert into MotClefVideo values (61,3);
insert into MotClefVideo values (61,9);
insert into MotClefVideo values (61,11);
insert into MotClefVideo values (62,3);
insert into MotClefVideo values (62,9);
insert into MotClefVideo values (62,11);
insert into MotClefVideo values (63,3);
insert into MotClefVideo values (63,9);
insert into MotClefVideo values (63,11);
insert into MotClefVideo values (64,3);
insert into MotClefVideo values (64,9);
insert into MotClefVideo values (64,11);
insert into MotClefVideo values (65,3);
insert into MotClefVideo values (65,9);
insert into MotClefVideo values (65,11);
insert into MotClefVideo values (66,3);
insert into MotClefVideo values (66,9);
insert into MotClefVideo values (66,11);
insert into MotClefVideo values (67,3);
insert into MotClefVideo values (67,9);
insert into MotClefVideo values (67,11);
insert into MotClefVideo values (68,3);
insert into MotClefVideo values (68,9);
insert into MotClefVideo values (68,11);
insert into MotClefVideo values (69,3);
insert into MotClefVideo values (69,9);
insert into MotClefVideo values (69,11);
insert into MotClefVideo values (70,3);
insert into MotClefVideo values (70,9);
insert into MotClefVideo values (70,11);
insert into MotClefVideo values (71,3);
insert into MotClefVideo values (71,9);
insert into MotClefVideo values (71,11);
insert into MotClefVideo values (72,3);
insert into MotClefVideo values (72,9);
insert into MotClefVideo values (72,11);
insert into MotClefVideo values (73,3);
insert into MotClefVideo values (73,9);
insert into MotClefVideo values (73,11);
insert into MotClefVideo values (74,3);
insert into MotClefVideo values (74,9);
insert into MotClefVideo values (74,11);
insert into MotClefVideo values (75,3);
insert into MotClefVideo values (75,9);
insert into MotClefVideo values (75,11);
insert into MotClefVideo values (76,3);
insert into MotClefVideo values (76,9);
insert into MotClefVideo values (76,11);
insert into MotClefVideo values (77,3);
insert into MotClefVideo values (77,9);
insert into MotClefVideo values (77,11);
insert into MotClefVideo values (78,3);
insert into MotClefVideo values (78,9);
insert into MotClefVideo values (78,11);
insert into MotClefVideo values (79,3);
insert into MotClefVideo values (79,9);
insert into MotClefVideo values (79,11);
insert into MotClefVideo values (80,6);
insert into MotClefVideo values (80,11);
insert into MotClefVideo values (81,6);
insert into MotClefVideo values (81,11);
insert into MotClefVideo values (82,6);
insert into MotClefVideo values (82,11);
insert into MotClefVideo values (83,6);
insert into MotClefVideo values (83,11);
insert into MotClefVideo values (84,6);
insert into MotClefVideo values (84,11);
insert into MotClefVideo values (85,6);
insert into MotClefVideo values (85,11);
insert into MotClefVideo values (86,6);
insert into MotClefVideo values (86,11);
insert into MotClefVideo values (87,6);
insert into MotClefVideo values (87,11);
insert into MotClefVideo values (88,6);
insert into MotClefVideo values (88,11);
insert into MotClefVideo values (89,6);
insert into MotClefVideo values (89,11);
insert into MotClefVideo values (90,6);
insert into MotClefVideo values (90,11);
insert into MotClefVideo values (91,6);
insert into MotClefVideo values (91,11);
insert into MotClefVideo values (92,6);
insert into MotClefVideo values (92,11);
insert into MotClefVideo values (93,6);
insert into MotClefVideo values (93,11);
insert into MotClefVideo values (94,6);
insert into MotClefVideo values (94,11);
insert into MotClefVideo values (95,6);
insert into MotClefVideo values (95,11);
insert into MotClefVideo values (96,6);
insert into MotClefVideo values (96,11);
insert into MotClefVideo values (97,10);
insert into MotClefVideo values (97,12);
insert into MotClefVideo values (98,10);
insert into MotClefVideo values (98,12);
insert into MotClefVideo values (99,12);
insert into MotClefVideo values (100,10);
insert into MotClefVideo values (100,12);


insert into Achat values (1,1);
insert into Achat values (1,2);
insert into Achat values (1,3);
insert into Achat values (1,4);
insert into Achat values (1,5);
insert into Achat values (1,6);
insert into Achat values (1,7);
insert into Achat values (1,10);
insert into Achat values (1,11);
insert into Achat values (1,12);
insert into Achat values (1,13);
insert into Achat values (1,14);
insert into Achat values (1,15);

insert into Location values(1,16,'2018-02-01','2018-02-08');
insert into Location values(1,17,'2018-02-01','2018-02-08');
insert into Location values(1,18,'2018-02-01','2018-02-08');
insert into Location values(1,19,'2018-02-01','2018-02-08');
insert into Location values(1,20,'2018-02-01','2018-02-08');
insert into Location values(1,21,'2018-02-01','2018-02-08');
insert into Location values(1,22,'2018-02-01','2018-02-08');
insert into Location values(1,23,'2018-02-01','2018-02-08');
insert into Location values(1,24,'2018-02-01','2018-02-08');
insert into Location values(1,25,'2018-02-01','2018-02-08');
insert into Location values(1,26,'2018-02-01','2018-02-08');
insert into Location values(1,27,'2018-02-01','2018-02-08');
insert into Location values(1,28,'2018-02-01','2018-02-08');
insert into Location values(1,29,'2018-02-01','2018-02-08');
insert into Location values(1,30,'2018-02-01','2018-02-08');
insert into Location values(1,31,'2018-02-20','2018-02-27');
insert into Location values(1,32,'2018-02-20','2018-02-27');
insert into Location values(1,33,'2018-02-20','2018-02-27');
insert into Location values(1,34,'2018-02-20','2018-02-27');
insert into Location values(1,35,'2018-02-20','2018-02-27');
insert into Location values(1,36,'2018-02-20','2018-02-27');
insert into Location values(1,37,'2018-02-20','2018-02-27');
insert into Location values(1,38,'2018-02-20','2018-02-27');
insert into Location values(1,39,'2018-02-21','2018-02-28');
insert into Location values(1,40,'2018-02-21','2018-02-28');
insert into Location values(1,41,'2018-02-21','2018-02-28');
insert into Location values(1,42,'2018-02-21','2018-02-28');
insert into Location values(1,43,'2018-02-21','2018-02-28');
insert into Location values(1,44,'2018-02-21','2018-02-28');
insert into Location values(1,45,'2018-02-21','2018-02-28');
insert into Location values(1,46,'2018-02-21','2018-02-28');
insert into Location values(1,47,'2018-02-21','2018-02-28');
insert into Location values(1,48,'2018-02-21','2018-02-28');
insert into Location values(1,49,'2018-02-22','2018-03-01');
insert into Location values(1,50,'2018-02-22','2018-03-01');
insert into Location values(1,51,'2018-02-22','2018-03-01');
insert into Location values(1,52,'2018-02-22','2018-03-01');
insert into Location values(1,53,'2018-02-22','2018-03-01');
insert into Location values(1,54,'2018-02-22','2018-03-01');
insert into Location values(1,55,'2018-02-22','2018-03-01');
insert into Location values(1,56,'2018-02-22','2018-03-01');
insert into Location values(1,57,'2018-02-22','2018-03-01');
insert into Location values(1,58,'2018-02-22','2018-03-01');
insert into Location values(1,59,'2018-02-22','2018-03-01');
insert into Location values(1,60,'2018-02-22','2018-03-01');


insert into ChiffreAffaire values(1,'2018-02-01',174.7);
insert into ChiffreAffaire values(2,'2018-02-20',123.92);
insert into ChiffreAffaire values(3,'2018-02-21',29.9);
insert into ChiffreAffaire values(4,'2018-02-22',35.88);






