Insert into Client (idClient,nomCLient,prenomClient,prenomCLient,pseudo,mdp,email) values (1,’Lenormand’,’Brian’,’Link91’,’kikou91’,’brian.lenormand@u-psud.fr’);
Insert into Client (idClient,nomCLient,prenomClient,prenomCLient,pseudo,mdp,email) values (2,’Pechdimaldjian’,’Mathilde’,’Totoro’,’123456789’,’mathilde.pechdimaldjian@u-psud.fr’);
Insert into Client (idClient,nomCLient,prenomClient,prenomCLient,pseudo,mdp,email) values (3,’Bouchaudon’,’Corentin’,’Kevindu93’,’djudjull’,’corentin.bouchaudon@u-psud.fr’);

insert into CategorieClient(idCategorieClient,nomCategorieClient)values (1,'inscrit');
insert into CategorieClient(idCategorieClient,nomCategorieClient)values (1,'premium');
insert into CategorieClient(idCategorieClient,nomCategorieClient)values (1,'administrateur');

insert into CompoClient(idClient, idCategorieClient) values (1,1);
insert into CompoClient(idClient, idCategorieClient) values (2,2);
insert into CompoClient(idClient, idCategorieClient) values (3,3);


insert into CategorieFilm(idCategorieFilm, nomCategorieFilm)values( 1,'Film');
insert into CategorieFilm(idCategorieFilm, nomCategorieFilm)values( 1,'Serie');
insert into CategorieFilm(idCategorieFilm, nomCategorieFilm)values( 1,'Documentaire');


insert into Film(idVideo,nomVideo,groupeVideo,numEpisode,resume,nbvue,nbtelechargement,prixAchat,prixLocation) values (1,'La Menace Fantome','Star Wars',1,'Avant de devenir un célèbre chevalier Jedi, et bien avant de se révéler l"’"âme la plus noire de la galaxie, Anakin Skywalker est un jeune esclave sur la planète Tatooine. La Force est déjà puissante en lui et il est un remarquable pilote de Podracer. Le maître Jedi Qui-Gon Jinn le découvre et entrevoit alors son immense potentiel.Pendant ce temps, l"’"armée de droïdes de l"’"insatiable Fédération du Commerce a envahi Naboo, une planète pacifique, dans le cadre d"’"un plan secret des Sith visant à accroître leur pouvoir. Pour défendre la reine de Naboo, Amidala, les chevaliers Jedi vont devoir affronter le redoutable Seigneur Sith, Dark Maul.',666, 66, 3.99,5.99);
insert into Film(idVideo,nomVideo,groupeVideo,numEpisode,resume,nbvue,nbtelechargement,prixAchat,prixLocation) values (2,'La Guerre des Clones','Star Wars',2,'Depuis le blocus de la planète Naboo par la Fédération du commerce, la République, gouvernée par le Chancelier Palpatine, connaît une véritable crise. Un groupe de dissidents, mené par le sombre Jedi comte Dooku, manifeste son mécontentement envers le fonctionnement du régime. Le Sénat et la population intergalactique se montrent pour leur part inquiets face à l"'"émergence d"'"une telle menace.Certains sénateurs demandent à ce que la République soit dotée d"'"une solide armée pour empêcher que la situation ne se détériore davantage. Parallèlement, Padmé Amidala, devenue sénatrice, est menacée par les séparatistes et échappe de justesse à un attentat. Le Padawan Anakin Skywalker est chargé de sa protection. Son maître, Obi-Wan Kenobi, part enquêter sur cette tentative de meurtre et découvre la constitution d"'"une mystérieuse armée de clones... ',2,1, 5.99,3.99);
insert into Film(idVideo,nomVideo,groupeVideo,numEpisode,resume,nbvue,nbtelechargement,prixAchat,prixLocation) values (3,'La Revanche Sith','Star Wars',3,'La Guerre des Clones fait rage. Une franche hostilité oppose désormais le Chancelier Palpatine au Conseil Jedi. Anakin Skywalker, jeune Chevalier Jedi pris entre deux feux, hésite sur la conduite à tenir. Séduit par la promesse d"'"un pouvoir sans précédent, tenté par le côté obscur de la Force, il prête allégeance au maléfique Darth Sidious et devient Dark Vador.Les Seigneurs Sith s"'"unissent alors pour préparer leur revanche, qui commence par l"'"extermination des Jedi. Seuls rescapés du massacre, Yoda et Obi Wan se lancent à la poursuite des Sith. La traque se conclut par un spectaculaire combat au sabre entre Anakin et Obi Wan, qui décidera du sort de la galaxie.',123,122, 3.99,5.99);
insert into Film(idVideo,nomVideo,groupeVideo,numEpisode,resume,nbvue,nbtelechargement,prixAchat,prixLocation) values (4,'La guerre des etoiles','Star Wars',4,'Il y a bien longtemps, dans une galaxie très lointaine... La guerre civile fait rage entre l"'"Empire galactique et l"'"Alliance rebelle. Capturée par les troupes de choc de l"'"Empereur menées par le sombre et impitoyable Dark Vador, la princesse Leia Organa dissimule les plans de l"'"Etoile Noire, une station spatiale invulnérable, à son droïde R2-D2 avec pour mission de les remettre au Jedi Obi-Wan Kenobi. Accompagné de son fidèle compagnon, le droïde de protocole C-3PO, R2-D2 s"'"échoue sur la planète Tatooine et termine sa quête chez le jeune Luke Skywalker. Rêvant de devenir pilote mais confiné aux travaux de la ferme, ce dernier se lance à la recherche de ce mystérieux Obi-Wan Kenobi, devenu ermite au coeur des montagnes désertiques de Tatooine... ',15000,12000, 2.99,4.99);
insert into Film(idVideo,nomVideo,groupeVideo,numEpisode,resume,nbvue,nbtelechargement,prixAchat,prixLocation) values (5,'L"'"empire contre attaque','Star Wars',5,' Malgré la destruction de l"'"Etoile Noire, l"'"Empire maintient son emprise sur la galaxie, et poursuit sans relâche sa lutte contre l"'"Alliance rebelle. Basés sur la planète glacée de Hoth, les rebelles essuient un assaut des troupes impériales. Parvenus à s"'"échapper, la princesse Leia, Han Solo, Chewbacca et C-3P0 se dirigent vers Bespin, la cité des nuages gouvernée par Lando Calrissian, ancien compagnon de Han. Suivant les instructions d"'"Obi-Wan Kenobi, Luke Skywalker se rend quant à lui vers le système de Dagobah, planète marécageuse où il doit recevoir l"'"enseignement du dernier maître Jedi, Yoda. Apprenant l"'"arrestation de ses compagnons par les stormtroopers de Dark Vador après la trahison de Lando, Luke décide d"'"interrompre son entraînement pour porter secours à ses amis et affronter le sombre seigneur Sith... ',18000,17000, 2.99,4.99);
insert into Film(idVideo,nomVideo,groupeVideo,numEpisode,resume,nbvue,nbtelechargement,prixAchat,prixLocation) values (6,'Le retour du Jedi','Star Wars',6,' L"'"Empire galactique est plus puissant que jamais : la construction de la nouvelle arme, l"'"Etoile de la Mort, menace l"'"univers tout entier... Arrêté après la trahison de Lando Calrissian, Han Solo est remis à l"'"ignoble contrebandier Jabba Le Hutt par le chasseur de primes Boba Fett. Après l"'"échec d"'"une première tentative d"'"évasion menée par la princesse Leia, également arrêtée par Jabba, Luke Skywalker et Lando parviennent à libérer leurs amis.Han, Leia, Chewbacca, C-3PO et Luke, devenu un Jedi, s"'"envolent dès lors pour une mission d"'"extrême importance sur la lune forestière d"'"Endor, afin de détruire le générateur du bouclier de l"'"Etoile de la Mort et permettre une attaque des pilotes de l"'"Alliance rebelle. Conscient d"'"être un danger pour ses compagnons, Luke préfère se rendre aux mains de Dark Vador, son père et ancien Jedi passé du côté obscur de la Force. ',18000,17000, 2.99,4.99);
insert into Film(idVideo,nomVideo,groupeVideo,numEpisode,resume,nbvue,nbtelechargement,prixAchat,prixLocation) values (7,'Le reveil de la Force','Star Wars',7,'Dans une galaxie lointaine, très lointaine, un nouvel épisode de la saga "Star Wars", 30 ans après les événements du "Retour du Jedi"',15000,12000, 9.99,12.99);
insert into Film(idVideo,nomVideo,groupeVideo,numEpisode,resume,nbvue,nbtelechargement,prixAchat,prixLocation) values (8,'Les derniers jedi','Star Wars',8,' Les héros du Réveil de la force rejoignent les figures légendaires de la galaxie dans une aventure épique qui révèle des secrets ancestraux sur la Force et entraîne de surprenantes révélations sur le passé… ',8000,7000, 9.99,20.99);




