Insert into Client values (1,'Lenormand','Brian','Link91','kikou91','brian.lenormand@u-psud.fr');
Insert into Client values (2,'Pechdimaldjian','Mathilde','Totoro',123456789,'mathilde.pechdimaldjian@u-psud.fr');
Insert into Client values (3,'Bouchaudon','Corentin','Kevindu93','djudjull','corentin.bouchaudon@u-psud.fr');

insert into CategorieClient values (1,'inscrit');
insert into CategorieClient values (2,'premium');
insert into CategorieClient values (3,'administrateur');

insert into CompoClient values (1,1);
insert into CompoClient values (2,2);
insert into CompoClient values (3,3);


insert into CategorieVideo values( 1,'Film');
insert into CategorieVideo values( 2,'Serie');
insert into CategorieVideo values( 3,'Documentaire');


insert into Video values (1,'La Menace Fantome','Star Wars',1,'Avant de devenir un célèbre chevalier Jedi, et bien avant de se révéler l âme la plus noire de la galaxie, Anakin Skywalker est un jeune esclave sur la planète Tatooine. La Force est déjà puissante en lui et il est un remarquable pilote de Podracer. Le maître Jedi Qui-Gon Jinn le découvre et entrevoit alors son immense potentiel.Pendant ce temps, l armée de droïdes de l insatiable Fédération du Commerce a envahi Naboo, une planète pacifique, dans le cadre d n plan secret des Sith visant à accroître leur pouvoir. Pour défendre la reine de Naboo, Amidala, les chevaliers Jedi vont devoir affronter le redoutable Seigneur Sith, Dark Maul.',666, 66, 3.99,5.99);
insert into Video values (2,'La Guerre des Clones','Star Wars',2,'Depuis le blocus de la planète Naboo par la Fédération du commerce, la République, gouvernée par le Chancelier Palpatine, connaît une véritable crise. Un groupe de dissidents, mené par le sombre Jedi comte Dooku, manifeste son mécontentement envers le fonctionnement du régime. Le Sénat et la population intergalactique se montrent pour leur part inquiets face à l émergence d une telle menace.Certains sénateurs demandent à ce que la République soit dotée d une solide armée pour empêcher que la situation ne se détériore davantage. Parallèlement, Padmé Amidala, devenue sénatrice, est menacée par les séparatistes et échappe de justesse à un attentat. Le Padawan Anakin Skywalker est chargé de sa protection. Son maître, Obi-Wan Kenobi, part enquêter sur cette tentative de meurtre et découvre la constitution d une mystérieuse armée de clones... ',2,1, 5.99,3.99);
insert into Video values (3,'La Revanche Sith','Star Wars',3,'La Guerre des Clones fait rage. Une franche hostilité oppose désormais le Chancelier Palpatine au Conseil Jedi. Anakin Skywalker, jeune Chevalier Jedi pris entre deux feux, hésite sur la conduite à tenir. Séduit par la promesse d un pouvoir sans précédent, tenté par le côté obscur de la Force, il prête allégeance au maléfique Darth Sidious et devient Dark Vador.Les Seigneurs Sith s unissent alors pour préparer leur revanche, qui commence par l extermination des Jedi. Seuls rescapés du massacre, Yoda et Obi Wan se lancent à la poursuite des Sith. La traque se conclut par un spectaculaire combat au sabre entre Anakin et Obi Wan, qui décidera du sort de la galaxie.',123,122, 3.99,5.99);
insert into Video values (4,'La guerre des etoiles','Star Wars',4,'Il y a bien longtemps, dans une galaxie très lointaine... La guerre civile fait rage entre l Empire galactique et l Alliance rebelle. Capturée par les troupes de choc de l Empereur menées par le sombre et impitoyable Dark Vador, la princesse Leia Organa dissimule les plans de l Etoile Noire, une station spatiale invulnérable, à son droïde R2-D2 avec pour mission de les remettre au Jedi Obi-Wan Kenobi. Accompagné de son fidèle compagnon, le droïde de protocole C-3PO, R2-D2 s échoue sur la planète Tatooine et termine sa quête chez le jeune Luke Skywalker. Rêvant de devenir pilote mais confiné aux travaux de la ferme, ce dernier se lance à la recherche de ce mystérieux Obi-Wan Kenobi, devenu ermite au coeur des montagnes désertiques de Tatooine... ',15000,12000, 2.99,4.99);
insert into Video values (5,'L empire contre attaque','Star Wars',5,' Malgré la destruction de l Etoile Noire, l Empire maintient son emprise sur la galaxie, et poursuit sans relâche sa lutte contre l Alliance rebelle. Basés sur la planète glacée de Hoth, les rebelles essuient un assaut des troupes impériales. Parvenus à s échapper, la princesse Leia, Han Solo, Chewbacca et C-3P0 se dirigent vers Bespin, la cité des nuages gouvernée par Lando Calrissian, ancien compagnon de Han. Suivant les instructions d Obi-Wan Kenobi, Luke Skywalker se rend quant à lui vers le système de Dagobah, planète marécageuse où il doit recevoir l enseignement du dernier maître Jedi, Yoda. Apprenant l arrestation de ses compagnons par les stormtroopers de Dark Vador après la trahison de Lando, Luke décide d interrompre son entraînement pour porter secours à ses amis et affronter le sombre seigneur Sith... ',18000,17000, 2.99,4.99);
insert into Video values (6,'Le retour du Jedi','Star Wars',6,' L Empire galactique est plus puissant que jamais : la construction de la nouvelle arme, l Etoile de la Mort, menace l univers tout entier... Arrêté après la trahison de Lando Calrissian, Han Solo est remis à l ignoble contrebandier Jabba Le Hutt par le chasseur de primes Boba Fett. Après l échec d une première tentative d évasion menée par la princesse Leia, également arrêtée par Jabba, Luke Skywalker et Lando parviennent à libérer leurs amis.Han, Leia, Chewbacca, C-3PO et Luke, devenu un Jedi, s envolent dès lors pour une mission d extrême importance sur la lune forestière d Endor, afin de détruire le générateur du bouclier de l Etoile de la Mort et permettre une attaque des pilotes de l Alliance rebelle. Conscient d être un danger pour ses compagnons, Luke préfère se rendre aux mains de Dark Vador, son père et ancien Jedi passé du côté obscur de la Force. ',18000,17000, 2.99,4.99);
insert into Video values (7,'Le reveil de la Force','Star Wars',7,'Dans une galaxie lointaine, très lointaine, un nouvel épisode de la saga "Star Wars", 30 ans après les événements du "Retour du Jedi"',15000,12000, 9.99,12.99);
insert into Video values (8,'Les derniers jedi','Star Wars',8,' Les héros du Réveil de la force rejoignent les figures légendaires de la galaxie dans une aventure épique qui révèle des secrets ancestraux sur la Force et entraîne de surprenantes révélations sur le passé… ',8000,7000, 9.99,20.99);
insert into Video values (9,'Interstellar','',0,'Le film raconte les aventures d un groupe d’explorateurs qui utilisent une faille récemment découverte dans l espace-temps afin de repousser les limites humaines et partir à la conquête des distances astronomiques dans un voyage interstellaire.  ',20000,10000, 5.99,9.99);
insert into Video values (10,'My Little Pony: Le film','',0,'Quand le menaçant Storm King envahit Canterlot avec le plan de voler la magie aux poneys, le futur même d Equestria est en danger. Cette aventure inédite embarque les poneys à chercher du secours dans un voyage héroïque et plein d actions, au-delà des frontières de leurs foyers, à travers les montagnes magiques, les mondes sous-marins, et même dans un flamboyant bateau pirate volant. ',2,3, 0.99,2.99);
insert into Video values (11,'Mon Voisin Totoro','',0,'Deux petites filles viennent s installer avec leur père dans une grande maison à la campagne afin de se rapprocher de l hôpital ou séjourne leur mère. Elles vont découvrir l existence de créatures merveilleuses, mais très discrètes, les totoros. Le totoro est une créature rare et fascinante, un esprit de la forêt. Il se nourrit de glands et de noix. Il dort le jour, mais les nuits de pleine lune, il aime jouer avec des ocarinas magiques. Il peut voler et est invisible aux yeux des humains. ',5000,3000, 3.99,6.99);
insert into Video values (12,'Le Voyage de Chihiro','',0,'Chihiro, dix ans, a tout d une petite fille capricieuse. Elle s apprête à emménager avec ses parents dans une nouvelle demeure.Sur la route, la petite famille se retrouve face à un immense bâtiment rouge au centre duquel s ouvre un long tunnel. De l autre côté du passage se dresse une ville fantôme. Les parents découvrent dans un restaurant désert de nombreux mets succulents et ne tardent pas à se jeter dessus. Ils se retrouvent alors transformés en cochons.Prise de panique, Chihiro s enfuit et se dématérialise progressivement. L énigmatique Haku se charge de lui expliquer le fonctionnement de l univers dans lequel elle vient de pénétrer. Pour sauver ses parents, la fillette va devoir faire face à la terrible sorcière Yubaba, qui arbore les traits dune harpie méphistophélique.',15000,14000, 3.99,6.99);
insert into Video values (13,'Baby Driver','',0,'Chauffeur pour des braqueurs de banque, Baby a un truc pour être le meilleur dans sa partie : il roule au rythme de sa propre playlist. Lorsqu’il rencontre la fille de ses rêves, Baby cherche à mettre fin à ses activités criminelles pour revenir dans le droit chemin. Mais il est forcé de travailler pour un grand patron du crime et le braquage tourne mal… Désormais, sa liberté, son avenir avec la fille qu’il aime et sa vie sont en jeu.',11000,9000, 8.99,12.99);
insert into Video values (14,'Bienvenue chez les Chtis','',0,'Philippe Abrams est directeur de la poste de Salon-de-Provence. Il est marié à Julie, dont le caractère dépressif lui rend la vie impossible. Pour lui faire plaisir, Philippe fraude afin d obtenir une mutation sur la Côte d Azur. Mais il est démasqué: il sera muté à Bergues, petite ville du Nord.Pour les Abrams, sudistes pleins de préjugés, le Nord c est l horreur, une région glacée, peuplée d êtres rustres, éructant un langage incompréhensible, le "cheutimi". ',2000,1000, 3.99,5.99);
insert into Video values (15,'Les 11 Commandements','',0,'Le monde va mal, les humains ne rigolent plus, la situation est grave. Le Dieu de la blague n a plus qu une solution : Michaël Youn et sa bande.
Leur mission : accomplir " Les 11 commandements " de la blague pour remettre les peuples sur le droit chemin de la rigolade en repoussant les limites de la connerie. Danser la valse en apesanteur à 15 000 mètres d altitude, inonder une maison pour la transformer en piscine, jouer au beach volley avec une érection contrôlée, faire du roller sous somnifères... Rien n arrête Michaël Youn et sa bande, et en plus, ils le font pour de vrai ! ',500,100, 1.99,3.99);









